### ISSUE TITLE
Error while running benchmarks

### ISSUE THREAD

**Issue by nileshmali** [fastify/fastify-benchmarks#6]
I tried running fastify-benchmarks by installing it globaly it threw below error:

```
fastify-benchmark
⠼ Started bareexec error: Error: Command failed: node /home/nilesh/.nvm/versions/node/v8.4.0/lib/node_modules/fastify-benchmarks/node_modules/autocannon -c 100 -d 5 -p 10 localhost:3000
module.js:491
    throw err;
    ^

Error: Cannot find module '/home/nilesh/.nvm/versions/node/v8.4.0/lib/node_modules/fastify-benchmarks/node_modules/autocannon'
    at Function.Module._resolveFilename (module.js:489:15)
    at Function.Module._load (module.js:439:25)
    at Function.Module.runMain (module.js:609:10)
    at startup (bootstrap_node.js:158:16)
    at bootstrap_node.js:598:3

✔ Results for bare
{ Error: Command failed: node /home/nilesh/.nvm/versions/node/v8.4.0/lib/node_modules/fastify-benchmarks/node_modules/autocannon -c 100 -d 5 -p 10 localhost:3000
module.js:491
    throw err;
    ^

Error: Cannot find module '/home/nilesh/.nvm/versions/node/v8.4.0/lib/node_modules/fastify-benchmarks/node_modules/autocannon'
    at Function.Module._resolveFilename (module.js:489:15)
    at Function.Module._load (module.js:439:25)
    at Function.Module.runMain (module.js:609:10)
    at startup (bootstrap_node.js:158:16)
    at bootstrap_node.js:598:3

    at ChildProcess.exithandler (child_process.js:270:12)
    at emitTwo (events.js:125:13)
    at ChildProcess.emit (events.js:213:7)
    at maybeClose (internal/child_process.js:927:16)
    at Socket.stream.socket.on (internal/child_process.js:348:11)
    at emitOne (events.js:115:13)
    at Socket.emit (events.js:210:7)
    at Pipe._handle.close [as _onclose] (net.js:545:12)
  killed: false,
  code: 1,
  signal: null,
  cmd: 'node /home/nilesh/.nvm/versions/node/v8.4.0/lib/node_modules/fastify-benchmarks/node_modules/autocannon -c 100 -d 5 -p 10 localhost:3000' }
```

**Comment by cagataycali** [comment]
That's fixed now, thanks for your contributon 👍

**Comment by nileshmali** [comment]
Thank you.

**Comment by cagataycali** [comment]
I published a new version, you want to check it out? 🥇

**Comment by nileshmali** [comment]
Okay. Let me check now.

**Comment by nileshmali** [comment]
It is working now. Thanks.
I just realised that the command is now changed to `benchmark` but this may collide with another node module, I would suggest to keep previous name.
